site_name: Programaci贸n DAM
site_url: https://jmabadlopez.github.io/programacion/site/

nav:
  - Unidades:
    - UD1 - Introducci贸n a la programaci贸n. Lenguaje Java.: unidades/ud01.md
    - UD2 - Programaci贸n estructurada. Estructuras de control y repetici贸n: unidades/ud02.md
    - UD3 - Funciones y procedimientos: unidades/ud03.md
    - UD4 - Estructuras de datos din谩micas: unidades/ud04.md
    - UD5 - Programaci贸n Orientada a Objetos (POO): unidades/ud05.md
  - Ejercicios:
    - UD1: 
      - Ejercicios de introducci贸n: ejercicios/ud01/introduccion.md
      - Ejercicios del lenguaje Java: ejercicios/ud01/lenguaje_java.md
    - UD2:
      - Ejercicios de programaci贸n estructurada: ejercicios/ud02/ejercicios_ud02.md
      - Ejercicios de condicionales y bucles: ejercicios/ud02/ejercicios_ud02_bucles.md
      - Actividades entregables: ejercicios/ud02/entregable_ud02.md
    - UD3:
      - Ejercicios de funciones y procedimientos: ejercicios/ud03/ejercicios_ud03_inicio.md
      - Actividad entregable. Gestor de Inventario de Ferreteria: ejercicios/ud03/ejercicio_ud03_ferreteria.md
      - Actividad (EXTRA). Analizador de textos: ejercicios/ud03/ejercicio_ud03_analizador_texto.md
    - UD4:
      - Ejercicios de listas: ejercicios/ud04/ejercicios_ud4_arraylist_inicio.md
      - Ejercicios avanzados de listas: ejercicios/ud04/ejercicios_ud4_listas_avanzado.md
      - Ejercicios de conjuntos y mapas: ejercicios/ud04/ejercicios_ud4_set_map.md
      - Actividad entregable. La log铆stica de Santa Claus: ejercicios/ud04/ejercicios_ud4_entregable.md
    - UD5:
      - Ejercicios de iniciaci贸n de POO: ejercicios/ud05/ejercicios_ud05_inicio.md
  - Recursos:
    - Gu铆as:
      - Instalaci贸n IntelliJ: recursos/guia_intellij.md
    - Infograf铆as:
      - Bucles: recursos/bucles.html
      - Array List: recursos/arraylist.html
    - Algor铆tmica:
      - B谩sica: recursos/algoritmica_basica.md
      - M茅todo de la burbuja (ordenaci贸n): recursos/burbuja.html
      - Recursividad: recursos/recursividad.html
  - Presentaci贸n: index.md

repo_url: https://github.com/jmabadlopez/programacion
repo_name: jmabadlopez/programacion

theme:
  name: material
  language: es
  logo: ./assets/images/camp.png
  favicon: ./assets/images/camp.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  font: 
    code: Roboto Mono
  hljs_languages:
    - python
    - java
    - c
  features:
    - optimize
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Modo oscuro
      primary: red
      accent: red 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
      primary: red
      accent: red
markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/jmabadlopez/programacion
# plugins:
#   - to-pdf:
#       author: Jos茅 Manuel Abad L贸pez
#       copyright:  Creative Commons CC BY-SA 4.0 2025
#       cover_title: Programaci贸n
#       cover_subtitle: 1潞 DAM
#       toc_title: "Contenidos"
#       toc_level: 3
#       output_path: ../public/libro.pdf