site_name: Programación DAM
site_url: https://jmabadlopez.github.io/programacion/site/

nav:
  - Inicio: index.md
  - Unidades:
    - UD1 - Introducción a la programación. Lenguaje Java.: unidades/ud01.md
    - UD2 - Programación estructurada. Estructuras de control y repetición: unidades/ud02.md
    - UD3 - Funciones y procedimientos: unidades/ud03.md
  - Ejercicios:
    - UD1: 
      - Ejercicios de introducción: ejercicios/ud01/introduccion.md
      - Ejercicios del lenguaje Java: ejercicios/ud01/lenguaje_java.md
    - UD2:
      - Ejercicios de programación estructurada: ejercicios/ud02/ejercicios_ud02.md
      - Ejercicios de condicionales y bucles: ejercicios/ud02/ejercicios_ud02_bucles.md
      - Actividades entregables: ejercicios/ud02/entregable_ud02.md
    - UD3:
      - Ejercicios de funciones y procedimientos: ejercicios/ud03/ejercicios_ud03_inicio.md
  - Recursos:
    - Guías:
      - Instalación IntelliJ: recursos/guia_intellij.md
    - Infografías:
      - Bucles: recursos/bucles.html
    - Algorítmica:
      - Básica: recursos/algoritmica_basica.md
repo_url: https://github.com/jmabadlopez/programacion
repo_name: jmabadlopez/programacion

theme:
  name: material
  language: es
  logo: ./assets/images/camp.png
  favicon: ./assets/images/camp.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  hljs_languages:
    - python
    - java
    - c
  features:
    - navigation.top
    - optimize
    - content.code.copy
    - navigation.footer
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Modo oscuro
      primary: red
      accent: red 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
      primary: red
      accent: red
markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition