site_name: Programación DAM

nav:
  - Inicio: index.md
  - Unidades:
    - UD1 - Introducción a la programación. Lenguaje Java.: unidades/ud01.md
    - UD2 - Programación estructurada. Estructuras de control y repetición: unidades/ud02.md
  - Ejercicios:
    - UD1: 
      - Ejercicios de introducción: ejercicios/ud01/introduccion.md
      - Ejercicios del lenguaje Java: ejercicios/ud01/lenguaje_java.md
    - UD2:
      - Ejercicios de programación estructurada: ejercicios/ud02/ejercicios_ud02_revisada.md
  - Recursos:
    - Guía de instalación IntelliJ: recursos/guia_intellij.md
repo_url: https://github.com/jmabadlopez/programacion
repo_name: jmabadlopez/programacion

theme:
  name: material
  language: es
  logo: ./assets/images/camp.png
  icon: fontawesome/brands/mastodon
  hljs_languages:
    - python
    - java
    - c
  features:
    - navigation.top
    - optimize
    - content.code.copy
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Modo oscuro
      primary: red
      accent: red 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
      primary: red
      accent: red
markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences